const GOOGLE_DOCS_TEXT_CONVERSION_RATIO =  2.14285714;

const AppConstants = {
    BACKGROUND_IMAGE: {uri: "https://yahtzeerage.github.io/CYOA-Assets/assets/backgroundBanner.gif" },
    BACKGROUND_IMAGE_HEIGHT: 867,
    BACKGROUND_IMAGE_WIDTH: 1542,
    BUTTON_BORDER_WIDTH: 7,
    GOOGLE_DOCS_TEXT_CONVERSION_RATIO: GOOGLE_DOCS_TEXT_CONVERSION_RATIO,
    TILE_FONT_SIZE: 24 * GOOGLE_DOCS_TEXT_CONVERSION_RATIO,
    SUBTITLE_FONT_SIZE: 21 * GOOGLE_DOCS_TEXT_CONVERSION_RATIO,
    CLICK_FONT_SIZE: 14 * GOOGLE_DOCS_TEXT_CONVERSION_RATIO,
    LINE_SPACING: 1.15
};

export default AppConstants;